version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-todo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context:  ./node-todo
    container_name: nodejs-app
    ports:
      - "3000:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mongo-todo

volumes:
  mongo-data:
